### ISSUE TITLE
On the compiler structure

### ISSUE THREAD

**Issue by Azer0s** [MaximilianJugendForscht/GerCompiler#3]
This might seem weird (most likely because this looks like a discontinued project and you probably don´t even care about it anymore) but the compiler structure is a bit...unconventional.
Please don´t take that as an insult. As someone who builds compilers and interpreters themselves, I´ve done many mistakes before and I just wanted to show you some odd things in your project.

- Lack off lexer/parser structure
- Use of string operations
- Lack of BNF/EBNF

Again: Please don´t take this as an insult. I just stumbled uppon your project and noticed that....also I had nothing better to do...

**Comment by Wittmaxi** [comment]
Hi ;)

thanks for your feedback! 
This compiler is discontinued - but I never miss any opportunity to learn. 
I wont mess with the basic structure of my compiler anymore - I would only add commands that are needed - However, since im currently learning C++ in depth, nothing hinders me from trying to implement something similar with your additions (you can see my learning progress in another repo. lol)

You might have seen that i'm still a kid from what ive written in the repo - thus I am really thankful that you chose such diplomatic wording - Know however, that I am always willing to take any criticism, as long as it is constructive. In fact, I was already pretty annoyed, myself, about those points when I learned about how "real compilers" work. You must know that this project was a replica of my Interpreter I wrote, back then when my world was nothing but "Windoze is the best OS, Pascal can do everything, what is assembler?" and I used a really naive approach (retrospectively I find it quite elegant, even though It complicates about everything). 

I have yet one question to ask: What do you mean with BNF? Should I use the context free grammar for Mistakes checking or for parsing? 

I am really thankful for your honest feedback - and for you having taken time to correct my project. 
Once im done with learning unit testing, ima implement gerLang 2.0 :P
